name: first

on: push

jobs:

  job1:
    runs-on: ubuntu-latest
    name: First job
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: env | sort

  job2:
    runs-on: windows-latest
    name: Second job
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: "Get-ChiledItem Env: | Sort-Object Name"
